#!/bin/sh

# crontab
# 45 00 * * * sudo -i -u ec2-user /home/ec2-user/myob/style-guide/test/run-casper-tests

if [ -d /home/ec2-user ]; then
  cd /home/ec2-user/myob/style-guide
fi

# run all tests
find e2e -type f -name "*-test.js" -exec ./test/run-casper-test "{}" \;
