#!/bin/sh

# for aws server

# run single test file, and email file name if erroneous

# run-accessibility-test tabs
# run accessibility-test e2e/tests/components/tabs/tabs-test.js

EXIT_STATUS=0

# run accessibility tests
# eg access_lint audit http://myob.devfi.sh/content/myob/Tests/alerts.html
# remove folder & filename to create url fi they are there

rm /tmp/accessibility.txt

URL=`echo "$1" | awk '{ gsub(/.*components\//, "", $0); gsub (/\/.*$/, "", $0);  print "http://myob.devfi.sh/content/myob/Tests/" $0 ".html"}'`; pa11y --ignore="notice;warning" "$URL" > /tmp/accessibility.txt

# test for FAIL found
if [ $? -ne 0 ]; then
  EXIT_STATUS=1
  echo "Subject: MYOB FE Tests Accessibiliity $1" `TZ="Australia/Sydney" date` | cat - /tmp/accessibility.txt | sendmail -f peter.orum@razorfish.com -t peter.orum@razorfish.com
fi

exit $EXIT_STATUS

